# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
